version: 2.1
orbs:
  scan: panw-ns/prisma-cloud@dev:first
jobs:
  scan_iac: scan/prisma_cloud
  
workflows:
  scan:
    jobs:
      - scan_iac:
          prisma_cloud_api_url: https://api-sl.qa.prismacloud.io
          access_key: 1b27424a-2eaf-4a3e-8b53-dacdc666d8f6
          secret_key: PC_SECRET_KEY
