version: 2.1
orbs:
  scan: panw-ns/prisma-cloud@dev:first
jobs:
  scan_iac: scan/prisma_cloud
  
workflows:
  scan:
    jobs:
      - scan_iac:
          prisma_cloud_api_url: <prisma cloud api url>
          access_key: <prisma cloud access key>
          secret_key: PC_SECRET_KEY
          failure_criteria_high_severity: 1
          failure_criteria_medium_severity: 2
          failure_criteria_low_severity: 3
          failure_criteria_operator: and
